import './globals.css'
import '@mantine/core/styles.css'
import 'react-toastify/dist/ReactToastify.css'

import { Box, ColorSchemeScript, Flex, MantineProvider } from '@mantine/core'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Image from 'next/image'
import Link from 'next/link'
import { ToastContainer } from 'react-toastify'

import Logo from '@/app/assets/logo.png'

import { CreatePostButton } from './components/CreatePostButton'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'DompixelBlog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <MantineProvider>
          <Flex direction={'column'} h={'100vh'}>
            <Flex
              p="md"
              bg={'black'}
              align={'center'}
              justify={'space-between'}
            >
              <Link href={'/'}>
                <Image loading="lazy" src={Logo} alt="" width={220} />
              </Link>

              <CreatePostButton />
            </Flex>

            <Box p={'md'}>{children}</Box>

            <Flex p="md" bg={'black'} align={'center'} justify={'center'}>
              <Link
                href={'https://www.linkedin.com/in/wesleyestacio/'}
                style={{ color: 'white', opacity: 0.5, textDecoration: 'none' }}
                target="_blank"
              >
                Wesley Estacio
              </Link>
            </Flex>
          </Flex>
        </MantineProvider>
      </body>
    </html>
  )
}
